name: link_text_with_umlauts
description: Easy to use text widget for Flutter apps, which converts inlined URLs into clickable links. Allows custom styling. Now supporting umlauts!
version: 0.2.1
homepage: https://github.com/mbsdevape/link_text_with_umlauts

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
